# Author: @RZFeeser
# Introduction to Azure DevOp Pipelines for Terraform
#
# Resources:
# Examples by Microsoft - https://aka.ms/yaml

# anytime "main" branch is modified
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'YAML formatting allows running a multi-line script'

# This would only necessary if we needed to select a specific version of Terraform
#- task: TerraformInstaller@1
#  inputs:
#    terraformVersion: 'latest'

- task: TerraformCLI@1
  inputs:
    command: 'init'
    allowTelemetryCollection: true
  displayName: 'terraform init - install providers'

- task: TerraformCLI@1
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
  displayName: 'terraform validate - ensure valid configuration'

- task: TerraformCLI@1
  inputs:
    command: 'apply'
    allowTelemetryCollection: true
  displayName: 'terraform apply - run configuration'
